apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonSet
  namespace: mateapp
  labels:
    app: todoapp-healthcheck
spec:
  selector:
    matchLabels:
      app: todoapp-healthcheck
  template:
    metadata:
      labels:
        app: todoapp-healthcheck
    spec:
      containers:
        - name: busybox
          image: busyboxplus:curl
          command:
            - /bin/sh
            - -c
            - "while true; do curl -f http://todoapp-service:80/api/health; sleep 5; done"
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "200m"
              memory: "200Mi"